---
resources:
  - name: ci-update-self-git
    type: git
    icon: github
    source:
      uri: https://github.com/username-is-already-taken2/ci_update-self.git
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world2]

  - name: job-update-ci
    public: true
    plan:
      - get: ci-update-self-git
        trigger: false
      - set_pipeline: self
        file: ci-update-self-git/basic/pipeline.yml

